### ISSUE TITLE
How to use TriggerListner？

### ISSUE THREAD

**Issue by Alucardxy** [jlinn/quartz-redis-jobstore#14]
I need to do something in misfire of triggers,
but they doesn't fired "fireComplete" either "misFired".
I use them in RAMJobStore was right.
pls help me whether TriggerListener is SUPPORT!

**Comment by jlinn** [comment]
Yes, trigger listeners are supported.  

The Redis job store's misfire threshold was not adjustable, and was set to 60 seconds, which, depending on how late your job's execution was, may have been preventing your misfire listener from being called.  I just released version 1.1.4, which allows the `org.quartz.jobStore.misfreThreshold` property to be configured, and included [this test](https://github.com/jlinn/quartz-redis-jobstore/blob/master/src/test/java/net/joelinn/quartz/RedisJobStoreIntegrationTest.java) to ensure that it works.

**Comment by Alucardxy** [comment]
I have updated to version 1.1.4 ,but the problem still there.
My TriggerListener was not fired with any method, either "misfire" or "fireComlete".But when I commentted the configuration of jobstore(use RAMJobStrore),They are both fired!
How could I fix this?

**Comment by Alucardxy** [comment]
I have already finished it! IT'S MY FAULT!
I use the same trigger to listen triggers of different groups! So they are covered.
Sorry~~.

**Comment by jlinn** [comment]
Ah. No worries. Glad you got it figured out.
